### PR TITLE
Update link to test_helpers.py and missing grammer

### PR DESCRIPTION
**Pull request by kizzie**

### CODE REVIEW

**Comment by kizzie** [comment]
The second commit here to update the rules was me testing locally with Docker version 17.09.1-ce, build 19e2cf6 (not that it should make much of a difference) but the python code already sets all the keys to lower case so these were not working out the box

**Comment by kizzie** [comment]
Hmm, anyone about to take a look?

**Comment by georgyturevich** [comment]
@kizzie Hi,

Lukasz was on a personal leave. The code changes look good. I will try to test them in my env this or next week and will ask Lukasz to merge a PR if everything is ok.

**Comment by georgyturevich** [comment]
@piontec Hi Lukasz,

I tested the PR in my environment. It works correctly.

The most significant change here is https://github.com/piontec/docker-enforcer/pull/51/files#diff-6128ecd85ce44479392cdbb0203a25d9R197
```
-            self._client.stop(container.params['Id'])
+            self._client.stop(container.params['id'])
```

Looks like I forgot to change it when we decided to work with lowered indexes.

@kizzie Thanks again!

**Comment by piontec** [comment]
Hi @kizzie! Thanks for your patch. Unfortunately, I missed version bump after merging your patch. I did it now, on docker hub both 'latest' and 0.8.10 include it.

**Comment by kizzie** [comment]
Awesome, thank you!

**Pull request merged**
